# Generated by Django 3.1.6 on 2021-02-07 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_dreamreal_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='dreamreal',
            name='online',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.online'),
            preserve_default=False,
        ),
    ]
