# Generated by Django 3.1.6 on 2021-02-07 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_dreamreal_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dreamreal',
            name='online',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.online'),
        ),
    ]
